builds:
  - main: ./kernel
    id: "vertex-kernel"
    binary: vertex-kernel
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - "386"
      - amd64
      - arm
      - arm64

  - main: .
    id: "vertex"
    binary: vertex
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - "386"
      - amd64
      - arm
      - arm64
