name: SonarQube

on:
  push:
    branches:
      - dev

jobs:
  build:
    name: Run SonarQube
    runs-on: ubuntu-latest
    permissions: read-all
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Check if SonarQube is available, else skip the next steps
        id: availability
        run: |
          curl --head --fail --silent --location --output /dev/null ${{ secrets.SONAR_HOST_URL }} || OUT=$?
          if [ $OUT -ne 0 ]; then
            echo "SonarQube is not available, skipping."
            echo "SONAR_AVAILABLE=0" >> $GITHUB_OUTPUT
          else
            echo "SONAR_AVAILABLE=1" >> $GITHUB_OUTPUT
          fi

      - uses: sonarsource/sonarqube-scan-action@master
        if: steps.availability.outputs.SONAR_AVAILABLE == '1'
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
